apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tmgr-eks3
  region: eu-west-3
  version: "1.29"

iam:
  withOIDC: true

vpc:
  id: vpc-021490dfd686bd62e
  subnets:
    private:
      eu-west-3b:
        id: subnet-0b13d0ce97c312357
      eu-west-3c:
        id: subnet-079476718bf99b770

managedNodeGroups:
  - name: ng-app
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
    # 👇 Force les subnets privés
    subnets:
      - subnet-0b13d0ce97c312357
      - subnet-079476718bf99b770
    labels: { workload: app }

  - name: ng-gha
    instanceType: t3.small
    desiredCapacity: 0
    minSize: 0
    maxSize: 2
    privateNetworking: true
    subnets:
      - subnet-0b13d0ce97c312357
      - subnet-079476718bf99b770
    labels: { workload: gha }

  - name: ng-mon
    instanceType: t3.micro
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    privateNetworking: true
    subnets:
      - subnet-0b13d0ce97c312357
      - subnet-079476718bf99b770
    labels: { workload: mon }
