apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "task-manager.fullname" . }}-default-deny
  labels:
    app.kubernetes.io/name: {{ include "task-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
