apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-manager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "task-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "task-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
