replicaCount: 2

image:
  repository: nginxinc/nginx-unprivileged
  tag: "stable-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  host: taskmgr.example.com
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'

nodeSelector:
  workload: app

resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

serviceAccount:
  create: false
  name: ""
  annotations: {}

autoscaling:
  enabled: false
